# Workflow name
name: Backend Continuous Deployment

# Triggers for the workflow
on:
  # Manual trigger using the workflow_dispatch event
  workflow_dispatch:
  
  # Automatic trigger on push events to the main branch
  push:
    branches:
      - master


# Jobs defined in the workflow
jobs:
  test_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Install the dependencies.
      - run: cd starter/backend && npm ci
    
      - name: Run test only for main branch
        if: github.ref == 'refs/heads/master'
        # Run the test.
        run: cd starter/backend && npm test

  lint_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: latest
          cache: 'npm'

      # Install the dependencies.
      - run: cd starter/backend && npm ci
    
      - name: Run lint only for main branch
        if: github.ref == 'refs/heads/master'
        # Run the linter.
        run: cd starter/backend && npm run lint
      
  build_job:
    needs: [test_job, lint_job]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: latest
          cache: 'npm'

      # Install the dependencies.
      - run: cd starter/backend && npm ci
    
      - name: Run lint only for main branch
        if: github.ref == 'refs/heads/master'
        # Run the test.
        run: cd starter/backend && npm test