# Workflow name
name: Frontend Continuous Integration

# Triggers for the workflow
on:
  # Manual trigger using the workflow_dispatch event
  workflow_dispatch:
  
  # Automatic trigger on push events to the main branch
  push:
    branches:
      - master
  # Automatic trigger on pull request events targeting the main branch
  pull_request:
    branches:
      - master


# Jobs defined in the workflow
jobs:
  test_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Node.js 
        uses: actions/setup-node@v3
        with:
          node-version: latest

      # Install the dependencies.
      - run: cd starter/frontend && npm ci
    
      - name: Run test only for main branch
        if: github.ref == 'refs/heads/master'
        # Run the test.
        run: cd starter/frontend && npm test -- --passWithNoTests

  lint_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Node.js 
        uses: actions/setup-node@v3
        with:
          node-version: latest

      # Install the dependencies.
      - run: cd starter/frontend && npm ci
    
      - name: Run lint only for main branch
        if: github.ref == 'refs/heads/master'
        # Run the linter.
        run: cd starter/frontend && npm run lint -- --fix
      
  build-actions:
    needs: [test_job, lint_job]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Node.js 
        uses: actions/setup-node@v3
        with:
          node-version: latest

      # Install the dependencies.
      - run: cd starter/frontend && npm ci
    
      - name: Run lint only for main branch
        if: github.ref == 'refs/heads/master'
        # Run the test.
        run: cd starter/frontend && npm test -- --passWithNoTests

      # Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }} # Use your stored AWS Access Key ID
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }} # Use your stored AWS Secret Access Key
          aws-session-token: ${{secrets.AWS_SESSION_TOKEN}}
          aws-region: ${{ secrets.AWS_REGION }} # Use the region from your environment variables

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: frontend_ci
          IMAGE_TAG: frontend_ci_image
        run: |
          cd starter/frontend && docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          