# Workflow name
name: Frontend Continuous Deployment

# Triggers for the workflow
on:
  # Manual trigger using the workflow_dispatch event
  workflow_dispatch:
  
  # Automatic trigger on push events to the main branch
  #push:
    #branches:
      #- master


# Jobs defined in the workflow
jobs:
  test_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Install the dependencies.
      - run: cd starter/frontend && npm ci
    
      - name: Run test only for main branch
        if: github.ref == 'refs/heads/master'
        # Run the test.
        run: cd starter/frontend && npm test -- --passWithNoTests

  lint_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Install the dependencies.
      - run: cd starter/frontend && npm ci
    
      - name: Run lint only for main branch
        if: github.ref == 'refs/heads/master'
        # Run the linter.
        run: cd starter/frontend && npm run lint -- --fix
      
  build-actions:
    needs: [test_job, lint_job]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Install the dependencies.
      - run: cd starter/frontend && npm ci
    
      - name: Run lint only for main branch
        if: github.ref == 'refs/heads/master'
        # Run the test.
        run: cd starter/frontend && npm test -- --passWithNoTests